/**
 * This script was generated by Loon to simulate http requests.
 */

let url = "https://zxcstxt.com/wp-admin/admin-ajax.php";
let headers = {
    'sec-fetch-site':'same-origin',
    'cookie':['PHPSESSID=6n31r8q0si2jr39q8pfn4ehjsm; wordpress_logged_in_92d9558ea260eedb839b521a9f442ecd=damontian%7C1743216502%7Cjg0ocP5IqTiJrgcQI7L888JPw45x6n39pl9Of1p8VwX%7Cba0f8389e4b79838cccbeca5c5de10c68e68119c189d91c7b03b4f050b6e4118; cf_clearance=ny9sVEJCKBI9a6cFdQk32UbNF4iMPYIrXOXzSDioGNE-1742006897-1.2.1.1-OA8766R7KoMm6z6jEam1g9LYgB.O3cu2gsq2En83_XhpVAtXX6NsNYaVS8CgE9vUwdhhOpeQ6vYtRs340pEaBJbTWhkQT2HQC9Dcx6z8nAEjfxHaNv.x2DcI2sIIncWwskFGuTHyd2vP5.v_WyMF3LQPCUAaCKQvbh_vgGA4BenphvDLz0XjSryBthxvXPfAuErxeJq1oONRdUaoS2ccebFMrwt0RjdFVyZryUNS2Q452e8v.1.WS1rr6cgrWiQjwrjO8RkSvYO9mJ5.mkogtIRTenIpJSV5AYxFlpEGgDIwY1EiSjkTzcu6PPHKMM4z4.9mcP82MSIIr8eFq.bemC266y2vLdOBoGsE0YcqSOU; fps_accelerat=10;'],
    'user-agent':'Mozilla/5.0 (iPad; CPU OS 13_2_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/13.0 Mobile/13B14 Safari/604.1',
    'content-length':'19',
    'origin':'https://zxcstxt.com',
    'x-requested-with':'XMLHttpRequest',
    'sec-fetch-dest':'empty',
    'accept':'application/json, text/javascript, */*; q=0.01',
    'content-type':'application/x-www-form-urlencoded; charset=UTF-8',
    'referer':'https://zxcstxt.com/',
    'sec-fetch-mode':'cors',
    'accept-language':'zh-CN,zh-Hans;q=0.9',
    'accept-encoding':'gzip, deflate, br',
};

let body = "action=user_checkin";
var params = {
    url:url,
    timeout:50000,
    headers:headers,
    alpn:'h2',
    body:body,
};

$httpClient.post(params, function(errormsg,response,data) {
    if (errormsg) {
        console.log(errormsg);
    } else {
        console.log("Response Status: " + response.status);
        console.log("Response Headers: " + JSON.stringify(response.headers));
        console.log("Response Body: " + data);
    }
var nt = JSON.parse(data).msg;
$notification.post('知轩藏书(zxcstxt_dt)', '', nt);
    $done();
});